### ISSUE TITLE
We could not find tonik/gin package. You have to install it before using this theme. 

### ISSUE THREAD

**Issue by alisiddique** [tonik/theme#21]
How can i fix this?

**Comment by jedrzejchalubek** [comment]
Have you run `composer install` command?

tonik/gin is a dependency package which needs to be installed with a composer. You can verify if a package is actually installed in `vendor` directory. The should be `tonik/gin` folder.

**Comment by alisiddique** [comment]
Can i install manually without composer?

**Comment by jedrzejchalubek** [comment]
The `tonik/gin` package is prepared to be installed as a plugin too. You can clone `tonik/gin` repository to `wp-content/plugins/tonik-gin` folder and you will be able to see and activate it as a plugin. However you still need a composer to generate an autoloading file for the plugin itself.

So basically no, you cannot install starter without it. I really recommend you to manage it with a composer.

I think there are no benefits for installing it as a plugin as long as it won't receive updates like other plugins.

**Comment by alisiddique** [comment]
I got this following error-
Fatal error: syntax error, unexpected '}', expecting \\ (T_NS_SEPARATOR) in F:\SERVER\XAMP\htdocs\DEV\WP\WP_STARTER\wp-content\themes\custom-tonik\src\helpers.php on line 3

Line 3 : namespace {{ theme.namespace }};

And my installation process- 
https://pastebin.com/pYkvHJki

**Comment by jedrzejchalubek** [comment]
You have to run on PHP in the version at least 7.0. You may have lower version in your xamp setup

Additionally, I'm not sure why but you are installing old release (1.*) of the starter, maybe you should clear composer cache with `composer clearcache` and create project one more time. Make sure that `Installing tonik/gin (2.0.0): Downloading (100%)` show up when installing composer dependences.

**Comment by alisiddique** [comment]
Thanks for quick reply. I just follow this doc and it automatically downloaded older version.
http://labs.tonik.pl/theme/docs/installation/

And my bad my xamp PHP Version 5.6.30. Will try php 7

**Comment by mambax7** [comment]
Same error '''Fatal error: syntax error, unexpected '}', expecting \ (T_NS_SEPARATOR) in F:\SERVER\XAMP\htdocs\DEV\WP\WP_STARTER\wp-content\themes\custom-tonik\src\helpers.php on line 3''' on PHP 7.0.20 and PHP 7.1.6

**Comment by jedrzejchalubek** [comment]
@mambax7 @alisiddique Oh, I now what problem is. Please make sure you install starter with `composer create-project tonik/theme` command. There must be ***`tonik/theme`*** not `tonik/tonik`.

There was given `create-project` command with old repository name in the documentation.

Sorry about that :)

**Comment by mambax7** [comment]
On Windows we actually have to do following:
a) run: 
`npm install cross-env`

b) modify the code in package.js by adding "cross-env"  before NODE_ENV, so it looks like:

```
    "development": "cross-env NODE_ENV=development webpack --progress --hide-modules --config build/webpack.config.js",
    "production": "cross-env NODE_ENV=production webpack --progress --hide-modules --config build/webpack.config.js",
```

Then you can run the like: 
```
npm run prod
npm run dev 
```
This is based on advise from Susan-stack: https://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman/11928210

**Comment by jedrzejchalubek** [comment]
Thanks! Addressed this issue at https://github.com/tonik/theme/pull/23

**Comment by jedrzejchalubek** [comment]
Please, create a new issue if you have any further problems.

**Comment by Youdaman** [comment]
The docs (http://labs.tonik.pl/theme/docs/installation/) should include the hint by @mambax7 about running `npm install cross-env`

**Comment by c3730915** [comment]
> Have you run `composer install` command?
> 
> tonik/gin is a dependency which needs to be installed with a composer. You can verify if a package is actually installed in `vendor` directory. There should be `tonik/gin` folder.

Hello, I wanna know why I got the exception of [ErrorException]                                 
  putenv() has been disabled for security reasons when I tried to use composer to install it. I failed many times and I didn't get the solution. I would appreciate it if you help me. Thanks!
