### ISSUE TITLE
Might be nice to have a QuickStart guide in Readme 

### ISSUE THREAD

**Issue by GeorgeWL** [tonik/theme#24]
Just feel that having that documented will make it more user friendly.

**Comment by madebyaris** [comment]
They already have documentation, check it out http://labs.tonik.pl/theme/docs/

**Comment by jedrzejchalubek** [comment]
We removed quick start from README.md and referring directly to docs website. It easier for us to keep it in sync and up to date. 

Documentation has also its own repository (if you prefer markdown files): https://github.com/tonik/docs
