### ISSUE TITLE
Refactor service provider

### ISSUE THREAD

**Issue by zungx** [tonik/theme#27]
Hi @jedrzejchalubek 

My wordpress skill maybe not well, but i like this starter theme and i want contribute that. 
I have idea. If you accept, i will do it. 

Create new folder: 
- Services: This folder contain all class service.
>  Example: 
>  PostService.php -> this class management post
>  NotificationService.php -> this class management push notification to mobile, slack,...
>  ApiService.php -> this class for build rest api
> ...

- Providers: This folder contain all class will register, init services. 
>  Example: 
>  PostServiceProvide.php  -> we are init PostService here 
>  ApiServiceProvide.php -> we are init ApiService here
> ...

And we register all ServiceProvide in `theme.php`
example: 
```
$theme->register(App\Providers\PostServiceProvide::class);
$theme->register(App\Providers\ApiServiceProvide::class);
```
And package `tonik/gin` we will refactor binding, resolved method with class not a function.
In the feature we can using for `Dependency Injection`

Sorry my english not well :(

**Comment by jedrzejchalubek** [comment]
Our container service was not supposed to be fully featured DI or IoC Container. OOP in WordPress theme development world basically no exists, so this will bring a really little benefit.

You can see an `app/Setup/services.php` file as a service provider. If you don't want to store all of your bindings in this single file you are free to manage this in multiple files and separate folder. For example, create new `app/Providers/` folder and create topic related separation there. And autoload all files in theme config.

```
theme
   ├── app/
   │   ├── Http/ 
   │   │   ├── (...)
   │   ├── Setup/
   │   │   ├── (...)
   │   ├── Providers/
   │   │   ├── post.php    # Posts related services bindings
   │   │   ├── page.php   # Pages related services bindings
   │   │   ├── (...)
```

Currently, you can build your code in "OOP" fashion and use dependency injection when binding services. Here some academic example:

```php
class Foo {
    //
}
```

```php
class Bar
{
    public function __construct(Foo $foo) { 
        // 
    }
}
```

```php
theme()->bind('foo', function (Theme $theme) {
    return new Foo();
});
```

```php
theme()->bind('bar', function (Theme $theme) {
    return new Bar($theme['foo']);
});
```
