### ISSUE TITLE
Suggestion: rename 'partials/header.tpl.php' file

### ISSUE THREAD

**Issue by msacchetti** [tonik/theme#33]
When using an IDE like PHPStorm it gets confusing having two "header.tpl.php" files. 

Suggestion would be to change the 'partials/header.tpl.php" to something like 'post-header.tpl.php"

Thanks!

**Comment by jedrzejchalubek** [comment]
I think it would be better to rename `layouts/header.tpl.php` to maybe `layouts/head.tpl.php`(?). That way we will not be too specific.

Of course, a structure of the .tpl.php files is just starting boilerplate. You are free to change it to your needs :)

**Comment by msacchetti** [comment]
Makes sense to me, thanks
