### ISSUE TITLE
Concatenate / Combine JS

### ISSUE THREAD

**Issue by msacchetti** [tonik/theme#34]
I am new to webpack and i'm trying to figure out to to concat/combine JS files. I see a few plugins that can be used but I cant figure out how to fit it into the Tonik workflow. Any guidance would be appreciated!

**Comment by jedrzejchalubek** [comment]
When working with javascript ES6 you have to structure your js files a little differently. An overall workflow can be roughly compared to SASS. You have one main file where you import all other used components and this single main file is passed to the webpack to be compiled. 

Of course, you can have multiple main files which import different components.

You give really a little description what you want to achieve, so I can't give you any of concrete recommendations.

**Comment by msacchetti** [comment]
Thanks for the help. I understand the modular part of ES6 but not how to combine third party JS libraries. Say i'm using Foundation, Fontawesome. and ScrollMagic. Right now the JS folder looks like:

app.js
foundation.js
fontawesome.js
scrollmagic.js

Is there a way to "import" those third party scripts into the main app.js?

**Comment by msacchetti** [comment]
Another way to ask this question:

How can we have webpack output two files:

app.js
vendor.js

Where vendor.js is one file that concats all the third party libraries. My concern is to limit the amount of HTTP requests if we are using a large number of libraries. (My impression is many libraries can't be imported/required with ES6 i.e. Foundation)

**Comment by jedrzejchalubek** [comment]
You can create a single file for third party libraries and import them as modules inside. It sometimes gets a little tricky because not all scripts support ES6.

Then you can register these files in `config/app.json` in `assets` property. Items listed here will be outputted as separated files. More info in [docs](http://labs.tonik.pl/theme/docs/registering-stylesheets-and-scripts/)

Offcourse you can customize webpack config to your needs. It's impossible to cover every use case from the start.

**Comment by msacchetti** [comment]
Thanks again, the problem i was running into was the scripts i was using aren't es6 compatible so i was not able to import/export them in app.js. The answer was simple:

```
  "assets": {
    "app": [
        ...
    ],
    "vendor": [
      "./resources/assets/js/foundation.js",
      "./resources/assets/js/fontawesome.js",
      "./resources/assets/js/scrollMagic.js",
    ]
  },
```
