### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by alzearafat** [tonik/theme#35]
Hi there

I'm having an issue with Tonic. I'm following this tutorial : http://labs.tonik.pl/theme/docs/installation/

Everything runs smooth, but when I try to activate the theme, it become HTTP error 500, and I cannot open wp-admin. So I have to delete tonic theme folder.

I'm trying to increase PHP memory limit, but still no luck. I'm using MAMP by the way, with PHP 7.1.6.

Any help would be greatly appreciated

Thanks!

*[UPDATE]*

After activate WP_DEBUG and WP_DEBUG_LOG, I get this error instead : 
```
Parse error: syntax error, unexpected '}', expecting \\ (T_NS_SEPARATOR) in /Applications/MAMP/htdocs/web/wordpress/wp-content/themes/tonictheme/src/helpers.php on line 3
```

**Comment by jedrzejchalubek** [comment]
Are you using ^2.0.0 version of the starter?

It looks like you are using old version ^1.0.0 where you have to init starter with CLI before activating.

**Comment by alzearafat** [comment]
Thanks for the response

I'm installing using Composer.. So, where I can find the newest version?

Thank you

**Comment by jedrzejchalubek** [comment]
You can install it with composer with `composer require tonik/theme`. Afterwards just make sure that in `composer.json` file you have ^2.0.0 version

**Comment by alzearafat** [comment]
Thank you! :)
