### ISSUE TITLE
browsersync stuck loading localhost:3000

### ISSUE THREAD

**Issue by bongoman** [tonik/theme#36]
Mac OS X Sierra, running Local by Flywheel as the local dev environment.

`npm run watch` opens a browser tab at localhost:3000 but never loads.

Can access localhost:3001 to reach browsersync ui

Can also access tonik.dev directly just fine.

Thoughts on how to debug browsersync issue?

**Comment by bongoman** [comment]
Sorry, just realised I can proxy to tonik.dev in config/app.json

**Comment by jedrzejchalubek** [comment]
That's right :)

For clarification. A configuration of starter doesn't start any server by itself, it only tells browsersync to watch on a certain address. If that URL is different than standard localhost it should be setup in `config/app.json` at `settings.browserSync.proxy` property.
