### ISSUE TITLE
Starter should be shipped without any front-end boilerplate by default

### ISSUE THREAD

**Issue by jedrzejchalubek** [tonik/theme#37]
We plan to remove current front-end stack on Foundation, so the starter will ship without any by default. 

A developer will have the ability to spin different boilerplates on starter initializing with our CLI. This gives us the option to introduce various boilerplates (foundation, bootstrap, bulma etc.) and still give space for those who don't want any.

**Comment by alanmcginnis** [comment]
Please update the docs to reflect this change. Running into npm run dev errors when following setup instructions.

**Comment by jedrzejchalubek** [comment]
@alanmcginnis Please use a `master` branch (or better one of releases). 

We are following [this branching model](http://nvie.com/posts/a-successful-git-branching-model/). The main branch of the repo is `develop`, it is not a stable code.

Thanks for fast reaction :)

**Comment by msacchetti** [comment]
I will +1 for the option to use Bulma!

**Comment by cannap** [comment]
no it should ship with nothing :D i dont like to remove stuff and add my own or maybe a cli where you can generate and chose between some popular ones like bootstrap / bulma / foundation / none

**Comment by msacchetti** [comment]
@cannap That is what i meant, he said they are putting the options in the CLI so i voted to have Bulma included as a choice

**Comment by jedrzejchalubek** [comment]
That's right, CLI will ask for preset and generate required files.

Currently, I working on Foundation, Bootstrap and Bulma preset. Additionally, there are plans for Vue and React presets set up to use as hybrid apps (much like it is done in Laravel).

**Comment by cannap** [comment]
@msacchetti lol i should read a issue befor post something sry :P

**Comment by msacchetti** [comment]
Wow, very interesting. I've looked around for a WordPress/Vue integration with no luck. Having vue with this starter theme would be really cool to try out! Thanks for all your work

**Comment by MrTamagotchi** [comment]
Since we're on a wishing-spree I think it would be awesome if the CLI included options to include a JS testing framework of choice as well!

**Comment by cannap** [comment]
when yes ava test runer would be awesome

**Comment by kretek18** [comment]
Hi, is there any guide on how to use bootstrap?

**Comment by jedrzejchalubek** [comment]
The Foundation, Bootstrap, Bulma and Vue presets are ready to test with a [`develop`](https://github.com/tonik/theme). Would be great if someone from outside could take it for a test run :)

**Comment by mcglonelevi** [comment]
Is there any update on when the new presets will be merged to the master branch?  I am looking forward to this feature.

**Comment by jedrzejchalubek** [comment]
@mcglonelevi I didn't receive any issues according to the current `develop` branch (maybe nobody gives it a run). I will make the last test and probably release it in this week.

**Comment by jedrzejchalubek** [comment]
v2.1.0-rc.1 has been released: https://github.com/tonik/theme/releases/tag/v2.1.0-rc.1

You can create new project based on these release with `composer create-project tonik/theme:2.1.0-rc.1` command.
