### ISSUE TITLE
Syntax error when activate a theme

### ISSUE THREAD

**Issue by ikalangita** [tonik/theme#38]
Hello,

I followed the doc to install theme, i have the WP-CLI installed too but when i try to activate theme with = `wp theme activate my_theme` i got following error 

"Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or we can’t contact the database server at `localhost`. This could mean your host’s database server is down." 

My server is not down, i go to the wordpress backend, trying to activate manually theme and i got following error also :

`( ! ) Parse error: syntax error, unexpected '}', expecting \\ (T_NS_SEPARATOR) in /app/public/wp-content/themes/starter-theme/src/helpers.php on line 3`

Someone can help me?

Thanks

**Comment by jedrzejchalubek** [comment]
You have pulled old release of the starter. Make sure you have ^2.0.0 versions in your project composer.json file.

It also required to have PHP 7.0+ installed locally before creating a new project with `composer create-project tonik/theme` command. Clearing composer cache would be helpfull too `composer clearcache`.

**Comment by ikalangita** [comment]
Hello, 
Thank you for your response, i have php 7.0 locally, i created with `composer create-project tonik/theme` command. I followed the doc from the tonik website, it means that docs are not updated?

**Comment by jedrzejchalubek** [comment]
No, documentation is up to date. You have to have PHP 7+ otherwise composer will install an old release.

Yesterday, I've cleanup release so there should be no problem now. When someone will try to create a project on lower PHP version they should get a notice about the minimum version.

**Comment by septk** [comment]
I've error when activate Tonik. 

Failed to load resource: the server responded with a status of 404 (Not Found) app.js, app.css, foundations.... I don't understand why, I used npm run dev....

**Comment by jedrzejchalubek** [comment]
@septk Make sure build script does not return any errors and check if required files are actually outputted inside `public/` folder. Additionally, you can validate paths in assets registration in `app/Http/assets.php`.

I can't tell more without other information from you.

**Comment by nr1q** [comment]
I had the same issue, it only happens when using a backslash on the namespace with the CLI tool. I'll prepare a PR later on.
