### ISSUE TITLE
Theme to .zip command in cli

### ISSUE THREAD

**Issue by albinhubsch** [tonik/theme#41]
From the cli it would be nice to be able to create a theme.zip that can be distributed to clients or hosting of choice.

something like `vendor/bin/tonik make:zip` that runs `npm run prod` and then zips all theme file to a ready to share zip file.

**Comment by jedrzejchalubek** [comment]
A CLI job is only to initialize a theme and I want to keep it that way. There are a lot of more suitable libs for these kinds of functionalities (for example WP-CLI). Additionally, current implementation on CLImate doesn't give us the ability to define multiple commands.

I would recommend you to just create a simple bash script in your theme or create a WP-CLI plugin (maybe someone created it already).

**Comment by albinhubsch** [comment]
found a good plugin for this! you can close this.
