### ISSUE TITLE
Progressive Web App

### ISSUE THREAD

**Issue by crissoca** [tonik/theme#46]
Any plans to implement something like this on the framework? 

https://codeburst.io/progressive-web-app-with-webpack-198b073f6c74 it will be a nice enhancement

**Comment by jedrzejchalubek** [comment]
Can you tell more about benefits or use cases of this library when building WordPress theme? Looks like a specific solution for the specific type of projects.

**Comment by crissoca** [comment]
That link was only an example any script for that enable progressive web apps should do it.
I think of it as a nice extra since the starter is really robust already, the idea is to offer the base to also be able to build PWAs using the starter.

**Comment by msacchetti** [comment]
I think PWA is a very specific set of requirements that don't apply to every app, especially wordpress.  If I read correctly, a PWA is basically a term Google made you to describe apps with certain features - specifically using Service Workers. So applying this to a WordPress theme framework seems like it wouldn't really fit.  That is my 2 cents.

**Comment by jedrzejchalubek** [comment]
Closing for now. If anyone has
