### ISSUE TITLE
Yarn over NPM

### ISSUE THREAD

**Issue by jrah** [tonik/theme#54]
Is there a possibility to use [Yarn](https://yarnpkg.com/en/) over NPM in a future iteration? Yarn is exceptionally fast to load dependencies.

**Comment by GrzegorzRybkowski** [comment]
Hi jrah, you can use Yarn if you want to, I mean anyways you need to install Yarn locally on your computer and the only thing is keeping yarn.lock in our repository - which in my opinion 
does not make a difference

**Comment by jedrzejchalubek** [comment]
As far I know Yarn is a drop-in replacement for NPM. You are free to use it with the starter as long as you have it installed globally.

We keep locks files out of the repository, but they are not ignored. They will be generated and used once you run `npm install` or `yarn`.

**Comment by mcglonelevi** [comment]
I am using Tonik and yarn at work.  It is a drop-in replacement.

**Comment by nr1q** [comment]
Me too! BTW Yarn seems to be a little bit better when developing from both Linux and OSX, I didn't had dependency issues.
