### ISSUE TITLE
Question: Speeding up deployments?

### ISSUE THREAD

**Issue by drewrawitz** [tonik/theme#57]
I'm just looking at some ways to speed up the deployments, and I noticed in the docs and in the `travis.yml` file you are running both:

```
npm run development
npm run production
```

Is there a reason you need to run both? If you wanted to deploy to a production / staging environment it should be fine to just run `npm run production` correct?

Thanks!

**Comment by jedrzejchalubek** [comment]
Travis in the `tonik/theme` is set up as a test for starter building scripts. It's it gives us a confidence that scripts running correctly after each change in the code. They have slightly different setup so we run both.

If you want to use Travis as part of your ci/deploy pipeline you probably need to edit its settings to match your needs.

**Comment by drewrawitz** [comment]
Sounds good, just wanted to double check and make sure I wasn't missing anything. Thanks!
