### ISSUE TITLE
Unexpected behaviour of template()

### ISSUE THREAD

**Issue by lhermann** [tonik/theme#66]
Hi guys, thank you first of all for your awsome theme framework!

In my `single.php` controller I am doing this:

    use function AppTheme\template;
    template( [ 'single', get_query_var( 'post_type' ) ] );

### Expected behaviour
When I request /books/ for a custom post type `books` I expect it to first look for `single-books.tpl.php`, then for `single.tpl.php`, then throw an error.

### Actual behaviour
It looks for `single-books.tpl.php`, but then it looks for `single-.tpl.php`. The dash shouldn't be in there.

See here:

    Fatal error: Uncaught Tonik\Gin\Foundation\Exception\FileNotFoundException: Template file [resources/templates/single-.tpl.php] cannot be located. in /app/themefiles/vendor/tonik/gin/src/Gin/Template/Template.php on line 54```

**Comment by jedrzejchalubek** [comment]
This happens when you pass an empty string as a template name. We have to additionally check for an empty string.

```php
template(['single', '']);
```

For now, I would recommend you to create a post type specific controllers or check for an empty string at `get_query_var`.

Thanks for the greatly exemplary bug report :)

**Comment by jedrzejchalubek** [comment]
Fixed with [`tonik/gin:v2.0.3`](https://github.com/tonik/gin/releases/tag/v2.0.3) release

**Comment by lhermann** [comment]
Thank you for this quick response. Applied the update and can confirm that it is fixed!
