### ISSUE TITLE
Vue autoprefixer fix

### ISSUE THREAD

**Issue by msacchetti** [tonik/theme#71]
It looks like autoprefixer isnt working in single file Vue components. I got it working by changing the build/rules/vue.js to

    const config = require('../app.config')

    module.exports = {
      test: /\.vue$/,
      loader: 'vue-loader',
      options: {
        loaders: {
          scss: 'vue-style-loader!css-loader!sass-loader',
          sass: 'vue-style-loader!css-loader!sass-loader?indentedSyntax'
        },
        postcss: [
          require('autoprefixer')(config.settings.autoprefixer),
        ]
      }
    }

**Comment by jedrzejchalubek** [comment]
Confirm. Fixed with e78ed6d.
