### ISSUE TITLE
Browser reloading before changes made

### ISSUE THREAD

**Issue by joshNM** [tonik/theme#72]
I have an installation of the theme, and since adding more assets / importing more CSS modules, the browser seems to refresh before all of the changes have been made, meaning I have to do a manual refresh afterwards also...

I've tried adding more of a delay to BrowserSync, but without putting it to something like 5 seconds, the issue still persists...

Any help would be much appreciated!

Love the theme also!

**Comment by jedrzejchalubek** [comment]
Looks like some your local environment and project related problem, so it's really hard to help you :(

I can only suggest you experiment with options when initializing `BrowserSyncPlugin` inside `build/webpack.config.js` file.

Looking forward to a reply if you locate the problem.
