### ISSUE TITLE
Watching images folder for adding images

### ISSUE THREAD

**Issue by msacchetti** [tonik/theme#74]
When i save an image to the resources/assets/images folder, webpack notices the addition of the file but does not process it and add it to the public directory. Is there a setting that will make this happen?

**Comment by chrisschwartze** [comment]
Isn't that expected? I believe it shouldn't process images during `npm run watch` or `npm run dev`. It should only process/compress during `npm run prod`.

**Comment by msacchetti** [comment]
I was talking about when I'm developing the theme and I save an image to the resources/assets folder, I have to stop the watch process and rerun it because it does not get copied into the public folder (so subsequently the image path in my theme does not load, because it doesn't exist until I rerun watch).
