### ISSUE TITLE
Issue with asset_path

### ISSUE THREAD

**Issue by chrisschwartze** [tonik/theme#75]
Hey all,

Thanks for this great starter theme! Loving it so far.

I'm on a brand new WP install and a clean Tonik. 

I'm following the [docs](http://labs.tonik.pl/theme/docs/helper-functions/) and trying to: 

```
use function Tonik\Theme\App\asset;
$path = asset_path('css/app.css');
```

However, it returns: ` Fatal error: Uncaught Error: Call to undefined function asset_path()`

How come?

**Comment by chrisschwartze** [comment]
Never mind. Solved. 

There's a typo in the docs. Doing a pull request now.

**Comment by jedrzejchalubek** [comment]
There is an error in documentation. You have to import proper function name like this:

```php
use function Tonik\Theme\App\asset_path;
```
