### ISSUE TITLE
Migrate to Gulp instead of Webpack

### ISSUE THREAD

**Issue by jedrzejchalubek** [tonik/theme#83]
There are a lot of small issues when using Webpack primary as task runner. It will be more reliable to use Gulp and bring builder configuration from our other boilerplates: https://github.com/tonik/html-frontend-boilerplate

**Comment by austinpray** [comment]
What are you gonna use as the module bundler instead?

**Comment by jedrzejchalubek** [comment]
@austinpray [Rollup.js](https://rollupjs.org/). In our case, it will produce a smaller bundle files.

**Comment by sushidub** [comment]
You think you'll bring Gulp into the parent theme only? ...similar to how you structured the current version (with Webpack) where the child theme was left alone

**Comment by msacchetti** [comment]
I vote to keep webpack as these days most of the frameworks I use, are using webpack. Gulp is great but I don't see that toolset being used much anymore, in my experience, my 2 cents.

**Comment by chrisschwartze** [comment]
Some time has passed and I agree.

I’ve been using a ton of Laravel Mix lately on themes and WordPress plugins. This could possibly be integrated and reduce additional files as well.

>

**Comment by GrzegorzRybkowski** [comment]
why not getting rid of gulp and use node tools (sass, notify) and rollup under the hood for bundling scripts? What are the advantage of gulp?

**Comment by jedrzejchalubek** [comment]
We will stick to the Webpack 😄
