### ISSUE TITLE
Generating .pot files

### ISSUE THREAD

**Issue by lhermann** [tonik/theme#84]
Thanks for all the work with this theme, I love using it!

Could you share how you generated the `.pot` files in `resources/languages`?
I tries it with the WP-CLI like so: `wp i18n make-pot . resources/languages/my.pot`, but I was not successful :(

**Comment by lhermann** [comment]
I found the problem. Since the theme is using `config('textdomain')` as text domain argument, the `wp i18n make-pot` tool doesn't understand it. The solution is to add `--ignore-domain`. This is what I ended up with and it works perfectly!

```
wp i18n make-pot . resources/languages/my.pot --ignore-domain --exclude=node_modules,public,vendor
```

**Comment by jedrzejchalubek** [comment]
Yeah, some translating tools have problems when `textdomain` is defined as a variable in gettext functions. I think using `config('textdomain')` adds enough convenience that I tend to rather change the translating tool than using a static string here.

Everyone has to decide, starter does not force anyone to use a `config('textdomain')` here 😄
