### ISSUE TITLE
Gravity Forms doesn't load required assets

### ISSUE THREAD

**Issue by code23-isaac** [tonik/theme#87]
Hi,

Gravity Forms is not automatically loading the files it requires (as it should) - for instance if you have a date picker in your form, it should load datepicker.min.js and datepicker.min.css files from the plugin directory, but this isn't happening. I've had to enqueue gravityforms.min.js manually in assets.php to get form ajax to work.

Changed theme to Twentynineteen to troubleshoot and it behaves as expected.

Am I missing something here?

_P.S. Thanks for all your work on this great starter theme!_

**Comment by chrisschwartze** [comment]
Are you sure this is due to Tonik and not an error in your code? I have a site with 30 plugins and haven't run into this problem yet.

**Comment by code23-isaac** [comment]
After a bit more digging and testing, yes in fact nothing is amiss here.

From the GF docs:

> When embedding a form via a function call you must also manually include the necessary Gravity Forms related Javascript and CSS via the built in WordPress enqueue capabilities. Gravity Forms does not include these by default when calling a form via a function call and they are necessary for forms that contain conditional logic or the date picker field.

Solved by calling `gravity_form_enqueue_scripts()` within the `register_scripts()` function in `assets.php`.
