### ISSUE TITLE
examples for including bootstraps css and js?

### ISSUE THREAD

**Issue by v3nt** [tonik/theme#90]
Really keen to try this over the sage 9 setup (way too complicated) but can't see any tutorials for adding Bootstrap or other frameworks.

Would be good of the docs could be expanded to support this. And how to customise what parts of Bootstrap to bring in.

thanks.

**Comment by kristjankoppel** [comment]
Hi @v3nt 

If you use tonik CLI then you have an option to choose Bootstrap and everything will be installed for you. 
Please see http://labs.tonik.pl/theme/docs/configuration/ and part starting from "Initiating with CLI". Let us know if this helped you :)

**Comment by jedrzejchalubek** [comment]
As @kristjankoppel suggested you can look at presets in order to better know how we do it.

There is no one way of handling bootstrap, so I cannot give you a specific "step by step" recipe.
